### PR TITLE
Add MEC Coroutines and Timings API

### PR DESCRIPTION
**Pull request by Redforce04**
Note: This is the free version, and we have permission to use it in the api.

### CODE REVIEW

**Comment by KrayOristine** [comment]
What would this pr have use for?

**Comment by Redforce04** [comment]
> What would this pr have use for?

Its an "asynchronous" Timing API without using Asynchronous. This can be used by us and other developers to make more effective coroutines, and do various functions. 

For Instance:
```cs
public static void RunThings()
{
    Timing.CallDelayed(5f, () => {
        Log.Debug("This will be called after 5 seconds.");
    });
}
```
Or you can use the custom coroutines.
```cs
private CoroutineHandle _coolCoroutine;
public static void DoCoolCoroutine
{
    _coolCoroutine = Timing.RunCoroutine(DoCoroutine, "My Cool Coroutine");
}

public static void StopCoroutine()
{
    Timing.KillAllCoroutines(_coolCoroutine);
    Timing.KillAllCoroutine("My Cool Coroutine");
    
Timing.KillAllCoroutine();
}

public static IEnumerator<float> DoCoroutine()
{
    while(true)
    {
         Log.Debug("1 seconds waited.");
         yield return Timing.WaitForSeconds(1f);
         yield return Timing.WaitOneFrame(); // waits one frame.
    }
    CouroutineHandle handle = Timing.WaitForSeconds(12f, () => {
        Log.Debug("Wait for me!");
    });
    // Won't continue until the "Wait for me!" is displayed.
    yield return Timing.WaitUntilDone(handle);
}
```

**Comment by Redforce04** [comment]
I didn't mean to close this lol

**Comment by KrayOristine** [comment]
Look goods. Let hold it for now until is it needed.

**Comment by Redforce04** [comment]
Not all developers will use this, but some would find it very helpful. I personally would like to use it, and I feel like it's best to add it  to the api, so all our modders have access to the tool.

It's in the `MEC` namespace, so modders who have previously used this tool, can use it normally.

**Comment by Redforce04** [comment]
> Look goods. Let hold it for now until it is needed.

I need it for the main api for some other features

**Comment by KrayOristine** [comment]
> > Look goods. Let hold it for now until it is needed.
> 
> I need it for the main api for some other features

I think we might need to put it in ./MEC/**

**Comment by KrayOristine** [comment]
ok, every seem so good so far, approved

**Review by KrayOristine — APPROVED** [review]

**Pull request merged**
